import { AttireSet } from "./attireSets"

export const dangerAttireSet: AttireSet = {
    name: "Cute Animals",
    id: "danger",
    attributedTo: "Danger",
    attributedURL: "https://www.instagram.com/gemmamcshane/",
    iconPath: require("../../assets/attire/set-logos/Danger.png"),
    lightHexColor: "#ACD49D",
    darkHexColor: "#547846",
    attire: [
        {
            name: "Tie",
            id: "danger-tie",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/danger/Tie.png"),
            free: false,
            tier: 1,
            uuid: 37
        },
        {
            name: "Antlers",
            id: "danger-antlers",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/danger/antlers.png"),
            free: false,
            tier: 2,
            uuid: 38
        },
        {
            name: "A backpack",
            id: "danger-backpack",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/danger/backpack.png"),
            free: false,
            tier: 3,
            uuid: 39
        },
        {
            name: "A bike?!",
            id: "danger-bike",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/danger/bike.png"),
            free: false,
            tier: 3,
            uuid: 40
        },
        {
            name: "Black Hair",
            id: "danger-black-hair",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/danger/black-hair.png"),
            free: false,
            tier: 2,
            uuid: 41
        },
        {
            name: "Blonde Hair",
            id: "danger-blone-haior",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/danger/blone-haior.png"),
            free: false,
            tier: 3,
            uuid: 42
        },
        {
            name: "Brown Hair",
            id: "danger-brown-hair",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/danger/brown-hair.png"),
            free: false,
            tier: 3,
            uuid: 43
        },
        {
            name: "High Heels",
            id: "danger-shoe-two",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/danger/shoe-two.png"),
            free: false,
            tier: 1,
            uuid: 44
        },
        {
            name: "Shoeses",
            id: "danger-shoes",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/danger/shoes.png"),
            free: false,
            tier: 3,
            uuid: 45
        },
        {
            name: "A Skateboard",
            id: "danger-skateboard",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/danger/skateboard.png"),
            free: false,
            tier: 1,
            uuid: 46
        },
        {
            name: "Specs",
            id: "danger-specs",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/danger/specs.png"),
            free: false,
            tier: 2,
            uuid: 47
        },
        {
            name: "Some Wheels",
            id: "danger-wheels",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/danger/wheels.png"),
            free: false,
            tier: 2,
            uuid: 48
        },

        {
            name: "An Alient",
            id: "danger-alien",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/alien.png"),
            free: false,
            tier: 3,
            uuid: 49
        },
        {
            name: "Bee",
            id: "danger-bee",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/bee.png"),
            free: false,
            tier: 2,
            uuid: 50
        },
        {
            name: "Boar",
            id: "danger-boar",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/boar.png"),
            free: false,
            tier: 2,
            uuid: 51
        },
        {
            name: "A Boat",
            id: "danger-boat",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/boat.png"),
            free: false,
            tier: 3,
            uuid: 52
        },
        {
            name: "A Broome",
            id: "danger-broome",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/broome.png"),
            free: false,
            tier: 0,
            uuid: 53
        },
        {
            name: "A Cape",
            id: "danger-cape",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/bases/danger/cape.png"),
            free: false,
            tier: 1,
            uuid: 54
        },
        {
            name: "Cross Bones",
            id: "danger-crossbones",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/crossbones.png"),
            free: false,
            tier: 3,
            uuid: 55
        },
        {
            name: "Crow",
            id: "danger-crow",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/crow.png"),
            free: false,
            tier: 0,
            uuid: 56
        },
        {
            name: "Mini-Bus",
            id: "danger-cute-bus",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/cute-bus.png"),
            free: false,
            tier: 0,
            uuid: 57
        },
        {
            name: "An Egg",
            id: "danger-egg",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/egg.png"),
            free: false,
            tier: 0,
            uuid: 58
        },
        {
            name: "Elephant",
            id: "danger-elephant",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/elephant.png"),
            free: false,
            tier: 2,
            uuid: 59
        },
        {
            name: "Fawn",
            id: "danger-fawn",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/fawn.png"),
            free: false,
            tier: 3,
            uuid: 60
        },
        {
            name: "Fish",
            id: "danger-fish",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/Fish.png"),
            free: false,
            tier: 2,
            uuid: 61
        },
        {
            name: "Friend Egg",
            id: "danger-fried-egg",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/fried-egg.png"),
            free: false,
            tier: 0,
            uuid: 62
        },
        {
            name: "Ginger Hair",
            id: "danger-ginger-hair",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/bases/danger/ginger-hair.png"),
            free: false,
            tier: 2,
            uuid: 63
        },
        {
            name: "Big Heart",
            id: "danger-heart",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/heart.png"),
            free: false,
            tier: 1,
            uuid: 64
        },
        {
            name: "Chopper",
            id: "danger-helicopter",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/helicopter.png"),
            free: false,
            tier: 2,
            uuid: 65
        },
        {
            name: "Horse",
            id: "danger-horse",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/horse.png"),
            free: false,
            tier: 2,
            uuid: 66
        },
        {
            name: "Kangaroo",
            id: "danger-kangaroo",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/kangaroo.png"),
            free: false,
            tier: 1,
            uuid: 67
        },
        {
            name: "A Light Bulb",
            id: "danger-lightbulp",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/lightbulp.png"),
            free: false,
            tier: 2,
            uuid: 68
        },
        {
            name: "Lion",
            id: "danger-lion",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/lion.png"),
            free: false,
            tier: 0,
            uuid: 69
        },
        {
            name: "Mandarin Duck",
            id: "danger-mandarin-duck",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/mandarin-duck.png"),
            free: false,
            tier: 0,
            uuid: 70
        },
        {
            name: "Mole",
            id: "danger-mole",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/mole.png"),
            free: false,
            tier: 3,
            uuid: 71
        },
        {
            name: "Mouse",
            id: "danger-mouse",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/mouse.png"),
            free: false,
            tier: 1,
            uuid: 72
        },
        {
            name: "Narwhal",
            id: "danger-narwhal",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/narwhal.png"),
            free: false,
            tier: 1,
            uuid: 73
        },
        {
            name: "Octopus",
            id: "danger-octopus",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/octopus.png"),
            free: false,
            tier: 2,
            uuid: 74
        },
        {
            name: "Panda",
            id: "danger-panda",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/panda.png"),
            free: false,
            tier: 3,
            uuid: 75
        },
        {
            name: "Paperclippo",
            id: "danger-paperclip",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/paperclip.png"),
            free: false,
            tier: 0,
            uuid: 76
        },
        {
            name: "Parokeet",
            id: "danger-parokeet",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/parokeet.png"),
            free: false,
            tier: 3,
            uuid: 77
        },
        {
            name: "Parrot",
            id: "danger-parrot",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/parrot.png"),
            free: false,
            tier: 3,
            uuid: 78
        },
        {
            name: "Painguin",
            id: "danger-penguin",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/penguin.png"),
            free: false,
            tier: 2,
            uuid: 79
        },
        {
            name: "Danger Pig",
            id: "danger-pig",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/Pig.png"),
            free: false,
            tier: 0,
            uuid: 80
        },
        {
            name: "Racoon",
            id: "danger-racoon",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/racoon.png"),
            free: false,
            tier: 1,
            uuid: 81
        },
        {
            name: "Rainbow Bird",
            id: "danger-rainbow-bird",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/rainbow-bird.png"),
            free: false,
            tier: 3,
            uuid: 82
        },
        {
            name: "Rat",
            id: "danger-rat",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/rat.png"),
            free: false,
            tier: 3,
            uuid: 83
        },
        {
            name: "Red Panda",
            id: "danger-red-panda",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/red-panda.png"),
            free: false,
            tier: 1,
            uuid: 84
        },
        {
            name: "Rubber Duck",
            id: "danger-rubber-duck",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/rubber-duck.png"),
            free: false,
            tier: 2,
            uuid: 85
        },
        {
            name: "Seal",
            id: "danger-seal",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/seal.png"),
            free: false,
            tier: 0,
            uuid: 86
        },
        {
            name: "Snail",
            id: "danger-snail",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/snail.png"),
            free: false,
            tier: 2,
            uuid: 87
        },
        {
            name: "Snow Person",
            id: "danger-snowman",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/snowman.png"),
            free: false,
            tier: 1,
            uuid: 88
        },
        {
            name: "Squid",
            id: "danger-squid",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/squid.png"),
            free: false,
            tier: 3,
            uuid: 89
        },
        {
            name: "Tiger",
            id: "danger-tiger",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/tiger.png"),
            free: false,
            tier: 2,
            uuid: 90
        },
        {
            name: "Whale",
            id: "danger-whale",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/Whale.png"),
            free: false,
            tier: 1,
            uuid: 91
        },
        {
            name: "White Rabbit",
            id: "danger-white-rabbit",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/white-rabbit.png"),
            free: false,
            tier: 1,
            uuid: 92
        },
        {
            name: "Wolf!",
            id: "danger-wolf",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/wolf.png"),
            free: false,
            tier: 2,
            uuid: 93
        },
        {
            name: "Worm",
            id: "danger-worm",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/worm.png"),
            free: false,
            tier: 3,
            uuid: 94
        },
        {
            name: "Zebra",
            id: "danger-zebra",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/danger/zebra.png"),
            free: false,
            tier: 2,
            uuid: 95
        }
    ]
}
