import { AttireSet } from "./attireSets"

export const happyChapAttireSet: AttireSet = {
    name: "Chappo Packo",
    id: "happy-chap-pack",
    attributedTo: "The Happy Chappo",
    attributedURL: "https://www.facebook.com/thehappychappo/",
    iconPath: require("../../assets/attire/set-logos/HappyChappo.png"),
    lightHexColor: "#D49DBA",
    darkHexColor: "#994974",
    attire: [
        {
            name: "Alt Bird",
            id: "happy-chap-alt_default",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Alt_Default.png"),
            free: false,
            tier: 2,
            uuid: 96
        },
        {
            name: "Cthulupie",
            id: "happy-chap-cthulu_bird",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Cthulu_Bird.png"),
            free: false,
            tier: 0,
            uuid: 97
        },
        {
            name: "Baby Chick",
            id: "happy-chap-baby_chick",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Baby_Chick.png"),
            free: false,
            tier: 2,
            uuid: 98
        },
        {
            name: "Big Beako",
            id: "happy-chap-big_beak",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Big_Beak.png"),
            free: false,
            tier: 1,
            uuid: 99
        },
        {
            name: "Black Cat",
            id: "happy-chap-black_cat",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Black_Cat.png"),
            free: false,
            tier: 1,
            uuid: 100
        },
        {
            name: "Blue Chog",
            id: "happy-chap-bluechog",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/BlueChog.png"),
            free: false,
            tier: 0,
            uuid: 101
        },
        {
            name: "Blue Chick",
            id: "happy-chap-blue_chick",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Blue_Chick.png"),
            free: false,
            tier: 3,
            uuid: 102
        },
        {
            name: "Brainbow",
            id: "happy-chap-brainbow",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Brainbow.png"),
            free: false,
            tier: 2,
            uuid: 103
        },
        {
            name: "Bubblegum",
            id: "happy-chap-bubblegum",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Bubblegum.png"),
            free: false,
            tier: 3,
            uuid: 104
        },
        {
            name: "Chill Bird",
            id: "happy-chap-chilled_bird",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Chilled_Bird.png"),
            free: false,
            tier: 1,
            uuid: 105
        },
        {
            name: "Cooked",
            id: "happy-chap-cooked_2",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Cooked 2.png"),
            free: false,
            tier: 0,
            uuid: 106
        },
        {
            name: "Cooked",
            id: "happy-chap-cooked",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Cooked.png"),
            free: false,
            tier: 2,
            uuid: 107
        },
        {
            name: "Dog",
            id: "happy-chap-dog",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Dog.png"),
            free: false,
            tier: 1,
            uuid: 108
        },
        {
            name: "Earth",
            id: "happy-chap-earth",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Earth.png"),
            free: false,
            tier: 3,
            uuid: 109
        },
        {
            name: "Elephant",
            id: "happy-chap-elephant_2",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Elephant 2.png"),
            free: false,
            tier: 3,
            uuid: 110
        },
        {
            name: "Elephant",
            id: "happy-chap-elephant",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Elephant.png"),
            free: false,
            tier: 2,
            uuid: 111
        },
        {
            name: "Evil Brain",
            id: "happy-chap-evil_brain_2",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Evil_Brain 2.png"),
            free: false,
            tier: 0,
            uuid: 112
        },
        {
            name: "Evil Brain",
            id: "happy-chap-evil_brain",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Evil_Brain.png"),
            free: false,
            tier: 1,
            uuid: 113
        },
        {
            name: "Evil Eye",
            id: "happy-chap-evil_eye",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Evil_Eye.png"),
            free: false,
            tier: 3,
            uuid: 114
        },
        {
            name: "Evil Eye",
            id: "happy-chap-eye_2",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Eye 2.png"),
            free: false,
            tier: 3,
            uuid: 115
        },
        {
            name: "Evil Eye",
            id: "happy-chap-eye_3",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Eye 3.png"),
            free: false,
            tier: 2,
            uuid: 116
        },
        {
            name: "Evil Eye",
            id: "happy-chap-eye",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Eye.png"),
            free: false,
            tier: 3,
            uuid: 117
        },
        {
            name: "Evil Fox",
            id: "happy-chap-fox",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Fox.png"),
            free: false,
            tier: 1,
            uuid: 118
        },
        {
            name: "Ginger Cat",
            id: "happy-chap-ginger_cat",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Ginger_Cat.png"),
            free: false,
            tier: 2,
            uuid: 119
        },
        {
            name: "Good Brain",
            id: "happy-chap-good_brain",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Good_Brain.png"),
            free: false,
            tier: 3,
            uuid: 120
        },
        {
            name: "Happy Bird",
            id: "happy-chap-happy_bird",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Happy_Bird.png"),
            free: false,
            tier: 2,
            uuid: 121
        },
        {
            name: "Hound Dog",
            id: "happy-chap-hound_dog",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Hound_Dog.png"),
            free: false,
            tier: 3,
            uuid: 122
        },
        {
            name: "Ikkle Chicken",
            id: "happy-chap-little_chicken",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Little_Chicken.png"),
            free: false,
            tier: 2,
            uuid: 123
        },
        {
            name: "Mars",
            id: "happy-chap-mars",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Mars.png"),
            free: false,
            tier: 0,
            uuid: 124
        },
        {
            name: "Moono Brow",
            id: "happy-chap-moono_brow",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Moono_Brow.png"),
            free: false,
            tier: 0,
            uuid: 125
        },
        {
            name: "Painguin",
            id: "happy-chap-penguin",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Penguin.png"),
            free: false,
            tier: 3,
            uuid: 126
        },
        {
            name: "Pigeon",
            id: "happy-chap-pigeon",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Pigeon.png"),
            free: false,
            tier: 2,
            uuid: 127
        },
        {
            name: "Pink Chick",
            id: "happy-chap-pink_chick",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Pink_Chick.png"),
            free: false,
            tier: 3,
            uuid: 128
        },
        {
            name: "Whistler",
            id: "happy-chap-plains",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Plains.png"),
            free: false,
            tier: 3,
            uuid: 129
        },
        {
            name: "Pro Racer",
            id: "happy-chap-pro_racer",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Pro_Racer.png"),
            free: false,
            tier: 3,
            uuid: 130
        },
        {
            name: "Punk Racer",
            id: "happy-chap-punk_racer",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Punk_Racer.png"),
            free: false,
            tier: 1,
            uuid: 131
        },
        {
            name: "Chick",
            id: "happy-chap-purple_chick_3",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Purple_Chick 3.png"),
            free: false,
            tier: 3,
            uuid: 132
        },
        {
            name: "Chick",
            id: "happy-chap-purple_chick_4",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Purple_Chick 4.png"),
            free: false,
            tier: 3,
            uuid: 133
        },
        {
            name: "Chick",
            id: "happy-chap-purple_chick",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Purple_Chick.png"),
            free: false,
            tier: 3,
            uuid: 134
        },
        {
            name: "Rabbit",
            id: "happy-chap-rabbit",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Rabbit.png"),
            free: false,
            tier: 3,
            uuid: 135
        },
        {
            name: "Rage Bird",
            id: "happy-chap-rage_bird",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Rage_Bird.png"),
            free: false,
            tier: 1,
            uuid: 136
        },
        {
            name: "Rainbow",
            id: "happy-chap-rainbow_cat",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Rainbow_Cat.png"),
            free: false,
            tier: 2,
            uuid: 137
        },
        {
            name: "Chick",
            id: "happy-chap-rainbow_chick",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Rainbow_Chick.png"),
            free: false,
            tier: 3,
            uuid: 138
        },
        {
            name: "Chick",
            id: "happy-chap-red_chick_2",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Red_Chick 2.png"),
            free: false,
            tier: 3,
            uuid: 139
        },
        {
            name: "Chick",
            id: "happy-chap-red_chick_3",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Red_Chick 3.png"),
            free: false,
            tier: 3,
            uuid: 140
        },
        {
            name: "Chick",
            id: "happy-chap-red_chick_4",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Red_Chick 4.png"),
            free: false,
            tier: 3,
            uuid: 141
        },
        {
            name: "Chick",
            id: "happy-chap-red_chick_5",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Red_Chick 5.png"),
            free: false,
            tier: 3,
            uuid: 142
        },
        {
            name: "Chick",
            id: "happy-chap-red_chick_6",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Red_Chick 6.png"),
            free: false,
            tier: 3,
            uuid: 143
        },
        {
            name: "Chick",
            id: "happy-chap-red_chick",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Red_Chick.png"),
            free: false,
            tier: 3,
            uuid: 144
        },
        {
            name: "Saber Tooth",
            id: "happy-chap-saber_tooth",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Saber_Tooth.png"),
            free: false,
            tier: 1,
            uuid: 145
        },
        {
            name: "Seagull",
            id: "happy-chap-seagull_eyebrow_bird",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Seagull_Eyebrow_Bird.png"),
            free: false,
            tier: 1,
            uuid: 146
        },
        {
            name: "Shy Bird",
            id: "happy-chap-shy_bird",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Shy_Bird.png"),
            free: false,
            tier: 0,
            uuid: 147
        },
        {
            name: "Sketchnook",
            id: "happy-chap-sketchnook_mascot_freebie",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Sketchnook_Mascot_Freebie.png"),
            free: false,
            tier: 2,
            uuid: 148
        },
        {
            name: "Skullbird",
            id: "happy-chap-skull_bird",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Skull_Bird.png"),
            free: false,
            tier: 0,
            uuid: 149
        },
        {
            name: "Snow Fox",
            id: "happy-chap-snow_fox",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Snow_Fox.png"),
            free: false,
            tier: 2,
            uuid: 150
        },
        {
            name: "Standard Cat",
            id: "happy-chap-standard_cat",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Standard_Cat.png"),
            free: false,
            tier: 3,
            uuid: 151
        },
        {
            name: "Sun",
            id: "happy-chap-sun",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Sun.png"),
            free: false,
            tier: 2,
            uuid: 152
        },
        {
            name: "Torture Cat",
            id: "happy-chap-tortoiseshell",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Tortoiseshell.png"),
            free: false,
            tier: 3,
            uuid: 153
        },
        {
            name: "Tough Bird",
            id: "happy-chap-tough_bird",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Tough_Bird.png"),
            free: false,
            tier: 2,
            uuid: 154
        },
        {
            name: "Turkey",
            id: "happy-chap-turkey",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Turkey.png"),
            free: false,
            tier: 3,
            uuid: 155
        },
        {
            name: "Yellow Chog",
            id: "happy-chap-yellowchog",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/YellowChog.png"),
            free: false,
            tier: 1,
            uuid: 156
        },
        {
            name: "Alien Llama",
            id: "happy-chap-zombie_alien_llama_2",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Zombie_Alien_Llama 2.png"),
            free: false,
            tier: 1,
            uuid: 157
        },
        {
            name: "Alien Llama",
            id: "happy-chap-zombie_alien_llama",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/Zombie_Alien_Llama.png"),
            free: false,
            tier: 2,
            uuid: 158
        },
        {
            name: "Ball",
            id: "happy-chap-ball",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/ball.png"),
            free: false,
            tier: 3,
            uuid: 159
        },
        {
            name: "Cat",
            id: "happy-chap-cat",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/cat.png"),
            free: false,
            tier: 3,
            uuid: 160
        },
        {
            name: "Dino",
            id: "happy-chap-dino",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/dino.png"),
            free: false,
            tier: 0,
            uuid: 161
        },
        {
            name: "Globe",
            id: "happy-chap-globe",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/globe.png"),
            free: false,
            tier: 2,
            uuid: 162
        },
        {
            name: "Moon",
            id: "happy-chap-moon",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/moon.png"),
            free: false,
            tier: 2,
            uuid: 163
        },
        {
            name: "Rock Rhino",
            id: "happy-chap-rockrhino",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/rockrhino.png"),
            free: false,
            tier: 3,
            uuid: 164
        },
        {
            name: "Tea Mug",
            id: "happy-chap-tea-mug",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/tea-mug.png"),
            free: false,
            tier: 1,
            uuid: 165
        },
        {
            name: "Toaster",
            id: "happy-chap-toaster",
            description: "TBD",
            fit: "tight",
            base: true,
            href: require("../../assets/bases/happy-chap/toaster.png"),
            free: false,
            tier: 1,
            uuid: 166
        },
        {
            name: "Eye Shades",
            id: "happy-chap-2_eye_shades",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/2_Eye_Shades.png"),
            free: false,
            tier: 1,
            uuid: 167
        },
        {
            name: "Bandit Mask",
            id: "happy-chap-bandit_mask",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Bandit_Mask.png"),
            free: false,
            tier: 3,
            uuid: 168
        },
        {
            name: "Beard",
            id: "happy-chap-beard_disguise",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Beard_Disguise.png"),
            free: false,
            tier: 3,
            uuid: 169
        },
        {
            name: "Mask",
            id: "happy-chap-blue_mask",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Blue_Mask.png"),
            free: false,
            tier: 3,
            uuid: 170
        },
        {
            name: "Bowler Hat",
            id: "happy-chap-bowler_hat",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Bowler_Hat.png"),
            free: false,
            tier: 3,
            uuid: 171
        },
        // {
        //     id: "happy-chap-brolly_2",
        //     description: "TBD",
        //     fit: "tight",
        //     base: false,
        //     href: require("../../assets/attire/happy-chap/Brolly 2.png"),
        //     free: false,
        //     tier: 3
        // },
        // {
        //     id: "happy-chap-brolly_3",
        //     description: "TBD",
        //     fit: "tight",
        //     base: false,
        //     href: require("../../assets/attire/happy-chap/Brolly 3.png"),
        //     free: false,
        //     tier: 3
        // },
        // {
        //     id: "happy-chap-brolly",
        //     description: "TBD",
        //     fit: "tight",
        //     base: false,
        //     href: require("../../assets/attire/happy-chap/Brolly.png"),
        //     free: false,
        //     tier: 3
        // },
        {
            name: "Chicken Hair",
            id: "happy-chap-chicken_hair",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Chicken_Hair.png"),
            free: false,
            tier: 1,
            uuid: 172
        },
        {
            name: "Crown",
            id: "happy-chap-crown",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Crown.png"),
            free: false,
            tier: 2,
            uuid: 173
        },
        {
            name: "Mask",
            id: "happy-chap-deep_blue_mask",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Deep_Blue_Mask.png"),
            free: false,
            tier: 2,
            uuid: 174
        },
        {
            name: "Disguise",
            id: "happy-chap-disguise",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Disguise.png"),
            free: false,
            tier: 2,
            uuid: 175
        },
        {
            name: "Face Scar",
            id: "happy-chap-face_scar",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Face_Scar.png"),
            free: false,
            tier: 3,
            uuid: 176
        },
        {
            name: "Flame Aura",
            id: "happy-chap-flame_aura",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Flame_Aura.png"),
            free: false,
            tier: 0,
            uuid: 177
        },
        {
            name: "Great Hair",
            id: "happy-chap-great_hair",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Great_Hair.png"),
            free: false,
            tier: 1,
            uuid: 178
        },
        {
            name: "Mask",
            id: "happy-chap-green_mask",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Green_Mask.png"),
            free: false,
            tier: 2,
            uuid: 179
        },
        {
            name: "Holiday Hat",
            id: "happy-chap-holiday_hat",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Holiday_Hat.png"),
            free: false,
            tier: 3,
            uuid: 180
        },
        {
            name: "Magic Hat",
            id: "happy-chap-magic_hat",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Magic_Hat.png"),
            free: false,
            tier: 2,
            uuid: 181
        },
        {
            name: "Mask",
            id: "happy-chap-mask",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Mask.png"),
            free: false,
            tier: 2,
            uuid: 182
        },
        {
            name: "Spare Leg",
            id: "happy-chap-meat_leg",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Meat_Leg.png"),
            free: false,
            tier: 3,
            uuid: 183
        },
        {
            name: "Mustache",
            id: "happy-chap-mustachio_",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Mustachio_.png"),
            free: false,
            tier: 2,
            uuid: 184
        },
        {
            name: "One Eye Shades",
            id: "happy-chap-one_eye_shades",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/One_Eye_Shades.png"),
            free: false,
            tier: 3,
            uuid: 185
        },
        {
            name: "Open Beak",
            id: "happy-chap-open_beak",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Open_Beak.png"),
            free: false,
            tier: 2,
            uuid: 186
        },
        {
            name: "Spangled Banner",
            id: "happy-chap-pixel_spangled_banner",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Pixel_Spangled_Banner.png"),
            free: false,
            tier: 0,
            uuid: 187
        },
        {
            name: "Rabbit Ears",
            id: "happy-chap-rabbit_ears",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Rabbit_Ears.png"),
            free: false,
            tier: 2,
            uuid: 188
        },
        {
            name: "Rainbow Bird",
            id: "happy-chap-rainbow_bird_2",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Rainbow_Bird 2.png"),
            free: false,
            tier: 3,
            uuid: 189
        },
        {
            name: "Bird",
            id: "happy-chap-rainbow_bird_3",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Rainbow_Bird 3.png"),
            free: false,
            tier: 3,
            uuid: 190
        },
        {
            name: "Bird",
            id: "happy-chap-rainbow_bird_4",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Rainbow_Bird 4.png"),
            free: false,
            tier: 3,
            uuid: 191
        },
        {
            name: "Bird",
            id: "happy-chap-rainbow_bird_5",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Rainbow_Bird 5.png"),
            free: false,
            tier: 3,
            uuid: 192
        },
        {
            name: "Bird",
            id: "happy-chap-rainbow_bird",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Rainbow_Bird.png"),
            free: false,
            tier: 3,
            uuid: 193
        },
        {
            name: "Rainfro",
            id: "happy-chap-rainfro_",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Rainfro_.png"),
            free: false,
            tier: 0,
            uuid: 194
        },
        {
            name: "Sentient Cap",
            id: "happy-chap-sentient_baseball_cap",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Sentient_Baseball_Cap.png"),
            free: false,
            tier: 1,
            uuid: 195
        },
        {
            name: "Sik Hat",
            id: "happy-chap-sik_hat",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Sik_Hat.png"),
            free: false,
            tier: 1,
            uuid: 196
        },
        {
            name: "Sparkle Aura",
            id: "happy-chap-sparkle_aura",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Sparkle_Aura.png"),
            free: false,
            tier: 0,
            uuid: 197
        },
        {
            name: "Stilts",
            id: "happy-chap-stilts",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Stilts.png"),
            free: false,
            tier: 2,
            uuid: 198
        },
        {
            name: "Unihorn",
            id: "happy-chap-unicorn_horn",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Unicorn_Horn.png"),
            free: false,
            tier: 2,
            uuid: 199
        },
        {
            name: "War Spoon",
            id: "happy-chap-war_spoon",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/War_Spoon.png"),
            free: false,
            tier: 1,
            uuid: 200
        },
        {
            name: "Mask",
            id: "happy-chap-yellow_mask",
            description: "TBD",
            fit: "tight",
            base: false,
            href: require("../../assets/attire/happy-chap/Yellow_Mask.png"),
            free: false,
            tier: 2,
            uuid: 201
        }
    ]
}
