# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlappyRoyale' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlappyRoyale
  pod 'Firebase/Core'

  pod 'IronSourceSDK', '~> 6'

  pod 'IronSourceUnityAdsAdapter'

  pod 'IronSourceAdMobAdapter'
  pod 'IronSourceFacebookAdapter'
  pod 'IronSourceVungleAdapter'
  pod 'IronSourceTapjoyAdapter'
  pod 'IronSourceChartboostAdapter'

  
#
#  # ADDDDSsssss
#  pod 'mopub-ios-sdk', '~> 5.0'
#
#  # AdColony
#  pod 'MoPub-AdColony-Adapters', '3.3.7.1'
#
#  # AppLovin
#  pod 'MoPub-Applovin-Adapters', '6.6.1.0'
#
#  # Chartboost
#  pod 'MoPub-Chartboost-Adapters', '7.5.0.0'
#
#  # Google (AdMob)
#  pod 'MoPub-AdMob-Adapters', '7.44.0.0'
#
#  # Vungle
#  pod 'MoPub-Vungle-Adapters', '6.3.2.5'
end

target 'Flappy Dev' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlappyRoyale
  pod 'Firebase/Core'

  pod 'IronSourceSDK', '~> 6'
end
