# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlappyRoyale' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlappyRoyale
  pod 'Firebase/Core'

  # ADDDDSsssss
  pod 'mopub-ios-sdk', '~> 5.0'
  pod 'AdColony'
  pod 'VungleSDK-iOS'
  pod 'AppLovinSDK'
  pod 'ChartboostSDK'
end
