# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

metadata_path "../../assets/fastlane/ios/metadata"
screenshots_path "../../assets/fastlane/ios/screenshots"