# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean

    increment_build_number(xcodeproj: "FlappyRoyale.xcodeproj")
    commit_version_bump(xcodeproj: "FlappyRoyale.xcodeproj")

    build_app(workspace: "FlappyRoyale.xcworkspace", scheme: "FlappyRoyale")
    upload_to_testflight
  end

  desc "Submit a new build and metadata to the App Store"
  lane :appstore do
    ensure_git_status_clean

    increment_build_number(xcodeproj: "FlappyRoyale.xcodeproj")
    commit_version_bump(xcodeproj: "FlappyRoyale.xcodeproj")

    build_app(workspace: "FlappyRoyale.xcworkspace", scheme: "FlappyRoyale")
    upload_to_app_store
  end

  lane :add_device do
    device_name = prompt(text: "Enter the device name: ")
    device_udid = prompt(text: "Enter the device UDID: ")
    device_hash = {}
    device_hash[device_name] = device_udid
    register_devices(
      devices: device_hash
    )
    refresh_profiles
  end

  lane :refresh_profiles do
    match(
      force_for_new_devices: true
  )
  end
end
